apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.app_name}}                 # Name of the application.
  namespace: default  # Namespace name.
  labels:
    app: {{cookiecutter.app_name}}
  annotations:
spec:
  selector:
    app: {{cookiecutter.app_name}}                # Route service traffic to pods with label keys and values matching this selector.
  ports:                                          # The list of ports that are exposed by this service
    - name: http
      port: 80                                    # The port that will be exposed by this service.
      targetPort: 8080                            # Number or name of the port to access on the pods targeted by the service.
      protocol: TCP
